In [ ]:
#NumPy Library
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

print(np.__version__)

arr = np.array((1, 2, 3, 4))
print(arr)

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

arr = np.array([[[1,2,3],[3,4,5]],[[1,2,3],[4,5,6]]])
print(arr)

a = np.array(42)
b = np.array([1, 2, 3, 4])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[3,4,5]],[[1,2,3],[4,5,6]]])

print(a.ndim, b.ndim, c.ndim, d.ndim)

#Sum of two nums in array
arr = np.array([1,2])
sum = 0
for i in arr:
    sum += i

print(sum)

arr = np.array([5, 2, 9, 4])
print(np.sort(arr))


arr = np.array([[9,2,3],[4,7,6]])
print(arr[0,1])


[1 2 3 4]
1.26.4
[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [4 5 6]]]
0 1 2 3
3
[2 4 5 9]
2
[[2 3 9]
 [4 6 7]]


In [83]:
#Pandas
import pandas as pd

mydataset = {
    'cars':["Maruti", "Volvo", "Ford"],
    'passings':[3,7,2]
}

myvar = pd.DataFrame(mydataset)
print(myvar)

print(pd.__version__)

     cars  passings
0  Maruti         3
1   Volvo         7
2    Ford         2
2.2.2
0    1
1    2
2    3
dtype: int64
x    42
y    42
z    42
dtype: int64
42


/var/folders/ps/94tl90gj0bxgk7s6czfs42kh0000gn/T/ipykernel_21096/1872156926.py:24: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(myvar[1])


In [91]:
import pandas as pd
num = [1, 2, 3]

myvar = pd.Series(num)
print(myvar)

myvar = pd.Series(a, index=["x", "y", "z"])
print(myvar)

0    1
1    2
2    3
dtype: int64
x    42
y    42
z    42
dtype: int64


In [111]:
import pandas as pd

calories = {"day1":421, "day2":380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

data = {
    "Name": ["Rohan", "Swati", "Priya"],
    "age":[25,26,31],
}

myvar = pd.DataFrame(data)
print(myvar)


print(myvar.loc[0])


data = {
    "calories": [420, 350, 390],
    "duration":[50,40,45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)

print(df.loc["day2"])

day1    421
day2    380
day3    390
dtype: int64
    Name  age
0  Rohan   25
1  Swati   26
2  Priya   31
Name    Rohan
age        25
Name: 0, dtype: object
      calories  duration
day1       420        50
day2       350        40
day3       390        45
calories    350
duration     40
Name: day2, dtype: int64
